export const ActionTypes = {
    ADD_SUBSTATION : "ADD_SUBSTATION",
    ALL_SUBSTATIONS : "ALL_SUBSTATIONS",
    REMOVE_SELECTED_SUBSTATION : "REMOVE_SELECTED_SUBSTATION",
    UPDATE_SUBSTATION : "UPDATE_SUBSTATION",
    CHANGE_STATE : "CHANGE_STATE",
    GET_BY_NAME : "GET_BY_NAME",

    ADD_DISCONNECTOR : "ADD_DISCONNECTOR",
    ALL_DISCONNECTORS : "ALL_DISCONNECTORS",
    REMOVE_SELECTED_DISCONNECTOR : "REMOVE_SELECTED_DISCONNECTOR",
    UPDATE_DISCONNECTOR : "UPDATE_DISCONNECTOR",
};