export const ActionTypes = {
    ADD_SUBSTATION : "ADD_SUBSTATION",
    ALL_SUBSTATIONS : "ALL_SUBSTATIONS",
    REMOVE_SELECTED_SUBSTATION : "REMOVE_SELECTED_SUBSTATION",
    UPDATE_SUBSTATION : "UPDATE_SUBSTATION",
    CHANGE_STATE : "CHANGE_STATE",
};