export const ActionTypes = {
    ADD_SUBSTATION : "ADD_SUBSTATION",
    ALL_SUBSTATIONS : "ALL_SUBSTATIONS",
    REMOVE_SELECTED_SUBSTATION : "REMOVE_SELECTED_SUBSTATION",
    UPDATE_SUBSTATION : "UPDATE_SUBSTATION",
    CHANGE_STATE : "CHANGE_STATE",
    GET_BY_NAME : "GET_BY_NAME",

    ADD_DISCONNECTOR : "ADD_DISCONNECTOR",
    ALL_DISCONNECTORS : "ALL_DISCONNECTORS",
    REMOVE_SELECTED_DISCONNECTOR : "REMOVE_SELECTED_DISCONNECTOR",
    UPDATE_DISCONNECTOR : "UPDATE_DISCONNECTOR",

    ADD_FUSE : "ADD_FUSE",
    ALL_FUSE : "ALL_FUSE",
    REMOVE_SELECTED_FUSE : "REMOVE_SELECTED_FUSE",
    UPDATE_FUSE : "UPDATE_FUSE",

    ADD_BREAKER : "ADD_BREAKER",
    ALL_BREAKERS : "ALL_BREAKERS",
    REMOVE_SELECTED_BREAKER: "REMOVE_SELECTED_BREAKER",
    UPDATE_BREAKER : "UPDATE_BREAKER",

    ADD_LOAD : "ADD_LOAD",
    ALL_LOAD : "ALL_LOAD",
    REMOVE_SELECTED_LOAD: "REMOVE_SELECTED_LOAD",
    UPDATE_LOAD : "UPDATE_LOAD",
};